{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "halfmoon.fullname" . }}
  labels:
    {{- include "halfmoon.labels" . | nindent 4 }}
type: Opaque
data:
  .security.yml: {{ .Values.credentials.security | toYaml | b64enc | quote }}
{{- end }}
